# Generated by Django 4.0.6 on 2022-08-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'Пользователь с таким номером телефона уже существует.'}, max_length=11, unique=True, verbose_name='phone number'),
        ),
    ]
