# Generated by Django 4.0.6 on 2022-08-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Название игрушки', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Цена игрушки', max_digits=10)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='Описание игрушки')),
                ('image_1', models.ImageField(blank=True, help_text='Изображений 1', upload_to='images/')),
                ('image_2', models.ImageField(blank=True, help_text='Изображений 2', upload_to='images/')),
                ('image_3', models.ImageField(blank=True, help_text='Изображений 3', upload_to='images/')),
                ('image_4', models.ImageField(blank=True, help_text='Изображений 4', upload_to='images/')),
                ('is_available', models.BooleanField(help_text='Имеется в наличии?')),
            ],
        ),
    ]
