# Generated by Django 4.0.6 on 2022-08-16 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='toy',
            options={'verbose_name': 'Название'},
        ),
        migrations.RenameField(
            model_name='toy',
            old_name='title',
            new_name='name',
        ),
    ]
