# Generated by Django 4.0.6 on 2022-08-02 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_toy_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='description',
            field=models.TextField(blank=True, help_text='Описание игрушки'),
        ),
        migrations.DeleteModel(
            name='ToyDescription',
        ),
    ]
