# Generated by Django 4.0.6 on 2022-08-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_alter_toy_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Цена игрушки', max_digits=10),
        ),
    ]
