# Generated by Django 4.0.6 on 2022-08-04 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0008_alter_toy_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='toy',
            name='image_2',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='toy',
            name='image_3',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='toy',
            name='image_4',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
