# Generated by Django 4.0.6 on 2022-08-04 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0009_rename_image_toy_image_1_toy_image_2_toy_image_3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toy',
            name='image_1',
            field=models.ImageField(help_text='Изображений 1', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='image_2',
            field=models.ImageField(blank=True, help_text='Изображений 2', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='image_3',
            field=models.ImageField(blank=True, help_text='Изображений 3', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='toy',
            name='image_4',
            field=models.ImageField(blank=True, help_text='Изображений 3', upload_to='images/'),
        ),
    ]
